### ISSUE TITLE
`Cannot use import statement outside a module` error when importing client

### ISSUE THREAD

**Issue by AlejandroEsquivel** [Boulevard/book-sdk#9]
When attempting to run the following code with typescript using Node version `12.14.0`

```node
import { Blvd } from "@boulevard/blvd-book-sdk";

(async()=>{
    const API_KEY='...'
    const BUSINESS_ID = '09cf52dc-a001-4b9f-9f4a-198ddf23dcad'
    const client = new Blvd(API_KEY, BUSINESS_ID);

    const business = await client.businesses.get();
    const locations = await business.getLocations();

    console.log(locations)
})();

```

I get the following error:

```
import { GraphQLClient, gql as gql$1 } from 'graphql-request';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/alejandro/Documents/upk/upk-api/scripts/adhoc/run.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Module.m._compile (/Users/alejandro/Documents/upk/upk-api/node_modules/ts-node/src/index.ts:392:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:995:10)
```

I have also tried the import statement: `const Blvd = require("@boulevard/blvd-book-sdk")` and obtained the same error.

My package JSON is the following:

```json
{
 "scripts": {
   "start": "ts-node app.ts",
    ...,
   "dependencies": {
        "@boulevard/blvd-book-sdk": "^1.0.37"
    },
   "devDependencies": {
      "ts-node": "3.3.0"
   } 
  }
}
```

**Comment by AlejandroEsquivel** [comment]
Also tried using node version `14.16.0` without typescript and managed to get a http call to the graph QL api with the following output:

```
(node:57513) UnhandledPromiseRejectionWarning: Error: GraphQL Error (Code: 200): {"response":{"error":"<!DOCTYPE html>\n<html class=\"h-full\" lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\">\n    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n    <meta name=\"description\" content=\"\">\n    <meta name=\"author\" content=\"\">\n    <title ng-bind=\"title\">Boulevard</title>\n    <link crossorigin=\"anonymous\"\n          href=\"https://unpkg.com/tailwindcss@1.2.0/dist/tailwind.min.css\"\n          integrity=\"sha384-E51zwM2RXfsr6dyVjhDmacr1PgikzlC+prmOn6JXe782mmAK847mRmUMYnicdKoZ\"\n          rel=\"stylesheet\">\n    <style>\n      @font-face {\n        font-family: \"BLVD\";\n        font-weight: 400;\n        font-style: normal;\n        src: url(\"https://static.joinboulevard.com/fonts/BasisGrotesquePro/BasisGrotesquePro-Regular.woff\") format(\"woff\"); }\n      \n      @font-face {\n        font-family: \"BLVD\";\n        src: local(\"Apple Color Emoji\"), local(\"Android Emoji\"), local(\"Segoe UI\"), local(EmojiSymbols), local(Symbola);\n        /* Emoji unicode blocks */\n        unicode-range: U+1F300-1F5FF, U+1F600-1F64F, U+1F680-1F6FF, U+2600-26FF; }\n      \n      @font-face {\n        font-family: \"BLVD\";\n        font-weight: 400;\n        font-style: italic;\n        src: url(\"https://static.joinboulevard.com/fonts/BasisGrotesquePro/BasisGrotesquePro-Italic.woff\") format(\"woff\"); }\n      \n      @font-face {\n        font-family: \"BLVD\";\n        src: local(\"Apple Color Emoji\"), local(\"Android Emoji\"), local(\"Segoe UI\"), local(EmojiSymbols), local(Symbola);\n        /* Emoji unicode blocks */\n        unicode-range: U+1F300-1F5FF, U+1F600-1F64F, U+1F680-1F6FF, U+2600-26FF; }\n      \n      @font-face {\n        font-family: \"BLVD\";\n        font-weight: 500;\n        font-style: normal;\n        src: url(\"https://static.joinboulevard.com/fonts/BasisGrotesquePro/BasisGrotesquePro-Medium.woff\") format(\"woff\"); }\n      \n      @font-face {\n        font-family: \"BLVD\";\n        src: local(\"Apple Color Emoji\"), local(\"Android Emoji\"), local(\"Segoe UI\"), local(EmojiSymbols), local(Symbola);\n        /* Emoji unicode blocks */\n        unicode-range: U+1F300-1F5FF, U+1F600-1F64F, U+1F680-1F6FF, U+2600-26FF; }\n      \n      @font-face {\n        font-family: \"BLVD\";\n        font-weight: 500;\n        font-style: italic;\n        src: url(\"https://static.joinboulevard.com/fonts/BasisGrotesquePro/BasisGrotesquePro-MediumItalic.woff\") format(\"woff\"); }\n      \n      @font-face {\n        font-family: \"BLVD\";\n        src: local(\"Apple Color Emoji\"), local(\"Android Emoji\"), local(\"Segoe UI\"), local(EmojiSymbols), local(Symbola);\n        /* Emoji unicode blocks */\n        unicode-range: U+1F300-1F5FF, U+1F600-1F64F, U+1F680-1F6FF, U+2600-26FF; }\n      \n      @font-face {\n        font-family: \"BLVD\";\n        font-weight: 700;\n        font-style: normal;\n        src: url(\"https://static.joinboulevard.com/fonts/BasisGrotesquePro/BasisGrotesquePro-Bold.woff\") format(\"woff\"); }\n      \n      @font-face {\n        font-family: \"BLVD\";\n        src: local(\"Apple Color Emoji\"), local(\"Android Emoji\"), local(\"Segoe UI\"), local(EmojiSymbols), local(Symbola);\n        /* Emoji unicode blocks */\n        unicode-range: U+1F300-1F5FF, U+1F600-1F64F, U+1F680-1F6FF, U+2600-26FF; }\n      \n      @font-face {\n        font-family: \"BLVD\";\n        font-weight: 700;\n        font-style: italic;\n        src: url(\"https://static.joinboulevard.com/fonts/BasisGrotesquePro/BasisGrotesquePro-BoldItalic.woff\") format(\"woff\"); }\n      \n      @font-face {\n        font-family: \"BLVD\";\n        src: local(\"Apple Color Emoji\"), local(\"Android Emoji\"), local(\"Segoe UI\"), local(EmojiSymbols), local(Symbola);\n        /* Emoji unicode blocks */\n        unicode-range: U+1F300-1F5FF, U+1F600-1F64F, U+1F680-1F6FF, U+2600-26FF; }\n      \n      @font-face {\n        font-family: \"BLVD Mono\";\n        font-weight: 400;\n        font-style: normal;\n        src: url(\"https://static.joinboulevard.com/fonts/BasisGrotesqueMonoPro/BasisGrotesqueMonoPro-Regular.woff\") format(\"woff\"); }\n      \n      @font-face {\n        font-family: \"BLVD Mono\";\n        src: local(\"Apple Color Emoji\"), local(\"Android Emoji\"), local(\"Segoe UI\"), local(EmojiSymbols), local(Symbola);\n        /* Emoji unicode blocks */\n        unicode-range: U+1F300-1F5FF, U+1F600-1F64F, U+1F680-1F6FF, U+2600-26FF; }\n      \n      @font-face {\n        font-family: \"BLVD Mono\";\n        font-weight: 700;\n        font-style: normal;\n        src: url(\"https://static.joinboulevard.com/fonts/BasisGrotesqueMonoPro/BasisGrotesqueMonoPro-Bold.woff\") format(\"woff\"); }\n      \n      @font-face {\n        font-family: \"BLVD Mono\";\n        src: local(\"Apple Color Emoji\"), local(\"Android Emoji\"), local(\"Segoe UI\"), local(EmojiSymbols), local(Symbola);\n        /* Emoji unicode blocks */\n        unicode-range: U+1F300-1F5FF, U+1F600-1F64F, U+1F680-1F6FF, U+2600-26FF;\n      }\n      \n      body {\n        background: url(/images/backgrounds/barbershop.jpg);\n        background-attachment: fixed;\n        background-position: 50%;\n        background-size: cover;\n        background-repeat: no-repeat;\n        font-family: \"BLVD\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\";\n        color: #41444a;\n        background-color: #f9f9fb;\n      }\n      \n      .logo-icon-container {\n        color: white;\n        font-weight: 300;\n        font-size: 2.5rem;\n        max-width: 100%;\n        box-sizing: border-box;\n        margin: 0;\n      }\n      \n      .logo-icon {\n        width: 250px;\n        color: white;\n        flex: 0 0 auto;\n        margin: 0;\n        min-width: 0;\n        min-height: 0;\n        fill: currentColor;\n        display: inline-block;\n        vertical-align: middle;\n        height: 24px;\n        background-repeat: no-repeat no-repeat;\n      }\n      \n      a {\n        color: #8698fe;\n      }\n      \n      \n      button[type=\"submit\"] {\n        background-color: #7c43fd;\n      }\n      \n      button[type=\"submit\"]:hover {\n        background-color: #8e5cfd;\n      }\n    </style>\n  </head>\n  <body class=\"h-full\">\n<div class=\"container mx-auto h-full flex justify-center items-center\">\n  <div>\n    <div class=\"flex items-center flex-col\">\n      <div class=\"logo-icon-container\">\n        <div class=\"logo-icon\" aria-label=\"Boulevard\" aria-hidden=\"true\">\n<svg viewBox=\"0 0 700 78\" fill=\"currentColor\" xmlns=\"http://www.w3.org/2000/svg\">\n  <path d=\"M113.24.44c-19.7 0-36.75 14.38-36.75 38.45 0 24.82 17 38.67 36.75 38.67 19.49 0 36.64-14 36.64-38.67 0-24.28-16.83-38.45-36.64-38.45zm0 62.2C102.48 62.64 93 54.12 93 38.89c0-14.91 9.05-23.64 20.24-23.64 11 0 20.23 9.05 20.23 23.64 0 15.34-9.26 23.75-20.23 23.75zM213.65 47.2c0 9.8-5.33 15.44-14.17 15.44-8.52 0-14.16-5.75-14.16-15.55V1.72h-16v46.12c0 20 11.93 29.61 30 29.61s30.25-9.91 30.25-29.72v-46h-16l.08 45.47zM270.88 1.72h-15.97v74.56h51.15V62.22h-35.18V1.72zM341.71 44.81h26.79V30.75h-26.79V15.78h35.15V1.72h-51.02v74.56h51.65V62.22h-35.78V44.81zM664.32 1.72h-26.63v74.56h26.52c18.32 0 35.79-12.15 35.79-37.81 0-25.03-17.36-36.75-35.68-36.75zm-.75 60.5h-10V15.78h9.7c6 0 10.86 2 14.58 6.18 3.72 4.18 5.65 9.58 5.65 16.51-.01 15.01-8 23.75-19.93 23.75zM49 34.56c2.83-2.53 4.65-7.62 4.65-11.39A21.68 21.68 0 0031.96 1.49H0v74.58H39.91a22.72 22.72 0 0022.72-22.71c0-8.49-4.55-16.17-13.63-18.8zM15.9 15.62h16.06a7.55 7.55 0 010 15.1H15.87l.03-15.1zm24 46.36h-24V44.82h24a8.58 8.58 0 110 17.16zM446 1.73L428.77 58.5h-2.39l-16.7-56.77h-16.03l21.94 74.55h23.85l22.63-74.55H446zM520.8 76.29h16L514.86 1.73H491l-22.63 74.56h16.06l6-19.9h24.43l5.94 19.9zm-26.17-33.47l7.08-23.31h2.38L511 42.82h-16.37zM602.23 45.71a23.894 23.894 0 001.363-39.278A23.889 23.889 0 00589.23 1.71h-32.08v74.55H573V49.52h14.75l8.91 26.75h16.87l-11.3-30.56zm-13-10.3h-16.25v-19.6h16.25a9.782 9.782 0 019.78 9.78 9.78 9.78 0 01-9.78 9.78v.04z\"/>\n</svg>\n\n        </div>\n      </div>\n    </div>\n    <div class=\"p-8 border-t-12 bg-white\">\n\n\n      <div class=\"text-gray-900 text-xl\">\n        Login to Boulevard\n      </div>\n      <p class=\"my-6 pr-16 text-gray-700 text-base\">\n        Enter your email address and password.\n      </p>\n<form action=\"/login\" method=\"post\"><input name=\"_csrf_token\" type=\"hidden\" value=\"WCIXHjYUIQJHAEcoIAA3CSV1MEpvKjxm0TrJSwNj6utwHdphF3XrWyt9\">\n\n      <div class=\"mb-4 w-full flex\">\n        <span class=\"p-2\">\n<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"22\" height=\"18\" viewBox=\"0 0 22 18\">\n  <g fill=\"none\" fill-rule=\"evenodd\" stroke=\"#000\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" transform=\"translate(1 1)\">\n    <path d=\"M2,0 L18,0 C19.1,0 20,0.9 20,2 L20,14 C20,15.1 19.1,16 18,16 L2,16 C0.9,16 0,15.1 0,14 L0,2 C0,0.9 0.9,0 2,0 Z\"/>\n    <polyline points=\"20 2 10 9 0 2\"/>\n  </g>\n</svg>\n\n        </span>\n<input class=\"flex-1 block appearance-none bg-white border-b border-grey-light hover:border-grey p-2\" id=\"email\" name=\"email\" placeholder=\"Email\" type=\"email\">\n      </div>\n      <div class=\"mb-4 w-full flex\">\n        <span class=\"p-2\">\n<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-lock\"><rect x=\"3\" y=\"11\" width=\"18\" height=\"11\" rx=\"2\" ry=\"2\"></rect><path d=\"M7 11V7a5 5 0 0 1 10 0v4\"></path></svg>\n        </span>\n<input class=\"flex-1 block appearance-none bg-white border-b border-grey-light hover:border-grey p-2\" id=\"password\" name=\"password\" placeholder=\"Password\" type=\"password\">\n      </div>\n<button class=\"w-full text-white py-2 px-4\" type=\"submit\">Login</button>\n</form>\n  </div>\n  <p class=\"text-white text-sm my-2 flex\">\n    <a class=\"w-full\" href=\"/reset-password-request\" class=\"no-underline\">Forgot Password?</a>\n\n  </p>\n</div>\n</div>\n\n  </body>\n</html>\n","status":200,"headers":{}},"request":{"query":"\n  \n  fragment BusinessProperties on Business {\n    avatar\n    id\n    insertedAt\n    name\n    tz\n    updatedAt\n    website\n  }\n\n  query Business {\n    business {\n      ...BusinessProperties\n    }\n  }\n"}}
    at /Users/alejandro/Documents/upk/upk-api/node_modules/graphql-request/dist/index.js:340:31
    at step (/Users/alejandro/Documents/upk/upk-api/node_modules/graphql-request/dist/index.js:63:23)
    at Object.next (/Users/alejandro/Documents/upk/upk-api/node_modules/graphql-request/dist/index.js:44:53)
    at fulfilled (/Users/alejandro/Documents/upk/upk-api/node_modules/graphql-request/dist/index.js:35:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:57513) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:57513) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by nlukic-blvd** [comment]
Hey @AlejandroEsquivel that error indicates that you are not authorized to access that endpoint, is your application authorized to access the business data, and also are you targeting the right environment?
